import { Source, WatchpointId } from '@/types';

// =============================================================================
// VERIFIED BLUESKY SOURCES - Generated 2026-01-15
// =============================================================================
// Sources have been audited and tiered:
// - T1 (Critical): Very active, fetch first
// - T2 (Standard): Semi-active, fetch async
// - T3 (Archive): Occasionally active, fetch on-demand
// =============================================================================

export type FetchTier = 'T1' | 'T2' | 'T3';

export interface TieredSource extends Source {
  feedUrl: string;
  fetchTier: FetchTier;
  postsPerDay: number;
}

// -----------------------------------------------------------------------------
// T1 - CRITICAL SOURCES (84) - Fetch first, always
// -----------------------------------------------------------------------------
export const tier1Sources: TieredSource[] = [
  // === BREAKING NEWS & OSINT (High-Activity) ===
  {
    id: 'noelreports',
    name: 'NOELREPORTS',
    handle: '@noelreports.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 95,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/noelreports.com',
    url: 'https://bsky.app/profile/noelreports.com',
    postsPerDay: 50,
  },
  {
    id: 'war-monitor',
    name: 'The War Monitor',
    handle: '@warmonitor.net',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/warmonitor.net',
    url: 'https://bsky.app/profile/warmonitor.net',
    postsPerDay: 25,
  },
  {
    id: 'bno-news',
    name: 'BNO News',
    handle: '@bnonews.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 95,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bnonews.com',
    url: 'https://bsky.app/profile/bnonews.com',
    postsPerDay: 15,
  },
  {
    id: 'malcontent-news',
    name: 'Malcontent News',
    handle: '@malcontentnews.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 85,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/malcontentnews.bsky.social',
    url: 'https://bsky.app/profile/malcontentnews.bsky.social',
    postsPerDay: 15,
  },
  {
    id: 'factal',
    name: 'Factal',
    handle: '@factal.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/factal.com',
    url: 'https://bsky.app/profile/factal.com',
    postsPerDay: 10,
  },
  {
    id: 'christopher-miller-ft',
    name: 'Christopher Miller (FT)',
    handle: '@christopherjm.ft.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 90,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/christopherjm.ft.com',
    url: 'https://bsky.app/profile/christopherjm.ft.com',
    postsPerDay: 5,
  },
  // === MAJOR NEWS WIRES (Jan 2026 - bluecrawler top 1000) ===
  {
    id: 'ap-news',
    name: 'The Associated Press',
    handle: '@apnews.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 95,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/apnews.com',
    url: 'https://bsky.app/profile/apnews.com',
    postsPerDay: 37.9,
  },
  {
    id: 'reuters',
    name: 'Reuters',
    handle: '@reuters.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 95,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/reuters.com',
    url: 'https://bsky.app/profile/reuters.com',
    postsPerDay: 100,
  },
  {
    id: 'mother-jones',
    name: 'Mother Jones',
    handle: '@motherjones.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/motherjones.com',
    url: 'https://bsky.app/profile/motherjones.com',
    postsPerDay: 32.6,
  },
  // === TOP JOURNALISTS (bluecrawler top 1000) ===
  {
    id: 'ron-filipkowski',
    name: 'Ron Filipkowski',
    handle: '@ronfilipkowski.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 85,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ronfilipkowski.bsky.social',
    url: 'https://bsky.app/profile/ronfilipkowski.bsky.social',
    postsPerDay: 16.6,
  },
  {
    id: 'kate-starbird',
    name: 'Kate Starbird',
    handle: '@katestarbird.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 90,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/katestarbird.bsky.social',
    url: 'https://bsky.app/profile/katestarbird.bsky.social',
    postsPerDay: 8.2,
  },
  {
    id: 'jim-acosta',
    name: 'Jim Acosta',
    handle: '@jimacosta.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 85,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jimacosta.bsky.social',
    url: 'https://bsky.app/profile/jimacosta.bsky.social',
    postsPerDay: 1.6,
  },
  {
    id: 'jen-rubin',
    name: 'Jen Rubin',
    handle: '@jenrubin.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 85,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jenrubin.bsky.social',
    url: 'https://bsky.app/profile/jenrubin.bsky.social',
    postsPerDay: 3.5,
  },
  {
    id: 'jake-tapper',
    name: 'Jake Tapper',
    handle: '@jaketapper.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 85,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jaketapper.bsky.social',
    url: 'https://bsky.app/profile/jaketapper.bsky.social',
    postsPerDay: 2.5,
  },
  // === NEW OSINT ACCOUNTS (Jan 2026) ===
  {
    id: 'eliot-higgins',
    name: 'Eliot Higgins',
    handle: '@eliothiggins.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 95,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/eliothiggins.bsky.social',
    url: 'https://bsky.app/profile/eliothiggins.bsky.social',
    postsPerDay: 43.3,
  },
  {
    id: 'wartranslated',
    name: 'WarTranslated (Dmitri)',
    handle: '@wartranslated.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 90,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/wartranslated.bsky.social',
    url: 'https://bsky.app/profile/wartranslated.bsky.social',
    postsPerDay: 28.2,
  },
  {
    id: 'covertshores',
    name: 'H I Sutton',
    handle: '@covertshores.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/covertshores.bsky.social',
    url: 'https://bsky.app/profile/covertshores.bsky.social',
    postsPerDay: 11.6,
  },
  {
    id: 'rebel44cz',
    name: 'Jakub Janovsky',
    handle: '@rebel44cz.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 85,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/rebel44cz.bsky.social',
    url: 'https://bsky.app/profile/rebel44cz.bsky.social',
    postsPerDay: 3.8,
  },
  {
    id: 'evergreen-intel',
    name: 'Evergreen Intel',
    handle: '@vcdgf555.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 85,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/vcdgf555.bsky.social',
    url: 'https://bsky.app/profile/vcdgf555.bsky.social',
    postsPerDay: 23.4,
  },
  {
    id: 'study-of-war',
    name: 'Institute for the Study of War',
    handle: '@thestudyofwar.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 90,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/thestudyofwar.bsky.social',
    url: 'https://bsky.app/profile/thestudyofwar.bsky.social',
    postsPerDay: 14.7,
  },
  {
    id: 'intel-night-owl',
    name: 'Intel Night OWL',
    handle: '@intelnightowl.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/intelnightowl.bsky.social',
    url: 'https://bsky.app/profile/intelnightowl.bsky.social',
    postsPerDay: 2,
  },
  // === ORIGINAL T1 SOURCES ===
  {
    id: 'van-jackson',
    name: 'Van Jackson',
    handle: '@vanjackson.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/vanjackson.bsky.social',
    url: 'https://bsky.app/profile/vanjackson.bsky.social',
    postsPerDay: 2.4,
  },
  {
    id: 'euan-macdonald',
    name: 'Euan MacDonald',
    handle: '@euanmacdonald.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/euanmacdonald.bsky.social',
    url: 'https://bsky.app/profile/euanmacdonald.bsky.social',
    postsPerDay: 4.5,
  },
  {
    id: 'andrew-revkin',
    name: 'Andrew Revkin',
    handle: '@revkin.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/revkin.bsky.social',
    url: 'https://bsky.app/profile/revkin.bsky.social',
    postsPerDay: 4.1,
  },
  {
    id: 'crisisgroup',
    name: 'International Crisis Group',
    handle: '@crisisgroup.org',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/crisisgroup.org',
    url: 'https://bsky.app/profile/crisisgroup.org',
    postsPerDay: 2.6,
  },
  {
    id: 'helen-branswell',
    name: 'Helen Branswell',
    handle: '@helenbranswell.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/helenbranswell.bsky.social',
    url: 'https://bsky.app/profile/helenbranswell.bsky.social',
    postsPerDay: 1.8,
  },
  {
    id: 'casey-newton',
    name: 'Casey Newton',
    handle: '@caseynewton.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/caseynewton.bsky.social',
    url: 'https://bsky.app/profile/caseynewton.bsky.social',
    postsPerDay: 3.2,
  },
  // === BLUECRAWLER TOP 1000 (Jan 2026) ===
  {
    id: 'nytimes',
    name: 'The New York Times',
    handle: '@nytimes.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/nytimes.com',
    url: 'https://bsky.app/profile/nytimes.com',
    postsPerDay: 78.6,
  },
  {
    id: 'atrupar',
    name: 'Aaron Rupar',
    handle: '@atrupar.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/atrupar.com',
    url: 'https://bsky.app/profile/atrupar.com',
    postsPerDay: 100,
  },
  {
    id: 'washingtonpost',
    name: 'The Washington Post',
    handle: '@washingtonpost.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/washingtonpost.com',
    url: 'https://bsky.app/profile/washingtonpost.com',
    postsPerDay: 46.5,
  },
  {
    id: 'hcrichardson',
    name: 'Heather Cox Richardson (TDPR)',
    handle: '@hcrichardson.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/hcrichardson.bsky.social',
    url: 'https://bsky.app/profile/hcrichardson.bsky.social',
    postsPerDay: 90.4,
  },
  {
    id: 'theguardian',
    name: 'The Guardian',
    handle: '@theguardian.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/theguardian.com',
    url: 'https://bsky.app/profile/theguardian.com',
    postsPerDay: 85.5,
  },
  {
    id: 'jamellebouie',
    name: 'jamelle',
    handle: '@jamellebouie.net',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jamellebouie.net',
    url: 'https://bsky.app/profile/jamellebouie.net',
    postsPerDay: 81.2,
  },
  {
    id: 'cnn',
    name: 'CNN',
    handle: '@cnn.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/cnn.com',
    url: 'https://bsky.app/profile/cnn.com',
    postsPerDay: 45.6,
  },
  {
    id: 'bencollins',
    name: 'Ben Collins',
    handle: '@bencollins.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bencollins.bsky.social',
    url: 'https://bsky.app/profile/bencollins.bsky.social',
    postsPerDay: 42.6,
  },
  {
    id: 'bloomberg',
    name: 'Bloomberg News',
    handle: '@bloomberg.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bloomberg.com',
    url: 'https://bsky.app/profile/bloomberg.com',
    postsPerDay: 56,
  },
  {
    id: 'politico',
    name: 'Politico',
    handle: '@politico.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/politico.com',
    url: 'https://bsky.app/profile/politico.com',
    postsPerDay: 48.1,
  },
  {
    id: 'financialtimes',
    name: 'Financial Times',
    handle: '@financialtimes.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/financialtimes.com',
    url: 'https://bsky.app/profile/financialtimes.com',
    postsPerDay: 56.2,
  },
  {
    id: 'theatlantic',
    name: 'The Atlantic',
    handle: '@theatlantic.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/theatlantic.com',
    url: 'https://bsky.app/profile/theatlantic.com',
    postsPerDay: 32.6,
  },
  {
    id: 'thebulwark',
    name: 'The Bulwark',
    handle: '@thebulwark.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/thebulwark.com',
    url: 'https://bsky.app/profile/thebulwark.com',
    postsPerDay: 74.7,
  },
  {
    id: 'politicoeu',
    name: 'POLITICO Europe',
    handle: '@politico.eu',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/politico.eu',
    url: 'https://bsky.app/profile/politico.eu',
    postsPerDay: 41.1,
  },
  {
    id: 'pbsnews',
    name: 'PBS News',
    handle: '@pbsnews.org',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/pbsnews.org',
    url: 'https://bsky.app/profile/pbsnews.org',
    postsPerDay: 33.7,
  },
  {
    id: 'nbcnews',
    name: 'NBC News',
    handle: '@nbcnews.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/nbcnews.com',
    url: 'https://bsky.app/profile/nbcnews.com',
    postsPerDay: 43,
  },
  {
    id: 'bylinetimes',
    name: 'Byline Times',
    handle: '@bylinetimes.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bylinetimes.bsky.social',
    url: 'https://bsky.app/profile/bylinetimes.bsky.social',
    postsPerDay: 10.5,
  },
  {
    id: 'thedailybeast',
    name: 'The Daily Beast',
    handle: '@thedailybeast.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/thedailybeast.bsky.social',
    url: 'https://bsky.app/profile/thedailybeast.bsky.social',
    postsPerDay: 75.6,
  },
  {
    id: 'huffpost',
    name: 'HuffPost',
    handle: '@huffpost.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/huffpost.com',
    url: 'https://bsky.app/profile/huffpost.com',
    postsPerDay: 71.4,
  },
  {
    id: 'cpsc',
    name: 'U.S. Consumer Product Safety Commission',
    handle: '@cpsc.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/cpsc.gov',
    url: 'https://bsky.app/profile/cpsc.gov',
    postsPerDay: 11,
  },
  {
    id: 'thetimes',
    name: 'The Times & Sunday Times',
    handle: '@thetimes.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/thetimes.com',
    url: 'https://bsky.app/profile/thetimes.com',
    postsPerDay: 63.8,
  },
  {
    id: 'latimes',
    name: 'Los Angeles Times',
    handle: '@latimes.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/latimes.com',
    url: 'https://bsky.app/profile/latimes.com',
    postsPerDay: 81.1,
  },
  {
    id: 'newsweek',
    name: 'Newsweek',
    handle: '@newsweek.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/newsweek.com',
    url: 'https://bsky.app/profile/newsweek.com',
    postsPerDay: 61.1,
  },
  {
    id: 'socialistdogmom',
    name: 'molly conger',
    handle: '@socialistdogmom.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/socialistdogmom.bsky.social',
    url: 'https://bsky.app/profile/socialistdogmom.bsky.social',
    postsPerDay: 18.6,
  },
  {
    id: 'npr',
    name: 'NPR',
    handle: '@npr.org',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/npr.org',
    url: 'https://bsky.app/profile/npr.org',
    postsPerDay: 28.7,
  },
  {
    id: 'propublica',
    name: 'ProPublica',
    handle: '@propublica.org',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/propublica.org',
    url: 'https://bsky.app/profile/propublica.org',
    postsPerDay: 16,
  },
  {
    id: 'gtconway',
    name: 'George Conway',
    handle: '@gtconway.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/gtconway.bsky.social',
    url: 'https://bsky.app/profile/gtconway.bsky.social',
    postsPerDay: 23.7,
  },
  {
    id: 'acyn',
    name: 'Acyn',
    handle: '@acyn.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/acyn.bsky.social',
    url: 'https://bsky.app/profile/acyn.bsky.social',
    postsPerDay: 16.8,
  },
  {
    id: 'cwarzel',
    name: 'Charlie Warzel',
    handle: '@cwarzel.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/cwarzel.bsky.social',
    url: 'https://bsky.app/profile/cwarzel.bsky.social',
    postsPerDay: 7.7,
  },
  {
    id: 'chrislhayes',
    name: 'Chris Hayes',
    handle: '@chrislhayes.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/chrislhayes.bsky.social',
    url: 'https://bsky.app/profile/chrislhayes.bsky.social',
    postsPerDay: 20.4,
  },
  {
    id: 'decodingfoxnews',
    name: 'Decoding Fox News',
    handle: '@decodingfoxnews.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/decodingfoxnews.bsky.social',
    url: 'https://bsky.app/profile/decodingfoxnews.bsky.social',
    postsPerDay: 8.8,
  },
  {
    id: 'swiftonsecurity',
    name: 'SwiftOnSecurity',
    handle: '@swiftonsecurity.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/swiftonsecurity.com',
    url: 'https://bsky.app/profile/swiftonsecurity.com',
    postsPerDay: 19.7,
  },
  {
    id: 'mollyjongfast',
    name: 'Molly Jong-Fast',
    handle: '@mollyjongfast.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/mollyjongfast.bsky.social',
    url: 'https://bsky.app/profile/mollyjongfast.bsky.social',
    postsPerDay: 16.5,
  },
  {
    id: 'theintercept',
    name: 'The Intercept',
    handle: '@theintercept.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/theintercept.com',
    url: 'https://bsky.app/profile/theintercept.com',
    postsPerDay: 12.2,
  },
  {
    id: 'vox',
    name: 'Vox',
    handle: '@vox.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/vox.com',
    url: 'https://bsky.app/profile/vox.com',
    postsPerDay: 8,
  },
  {
    id: 'marcelias',
    name: 'Marc Elias',
    handle: '@marcelias.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/marcelias.bsky.social',
    url: 'https://bsky.app/profile/marcelias.bsky.social',
    postsPerDay: 12.7,
  },
  {
    id: 'axios',
    name: 'Axios',
    handle: '@axios.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/axios.com',
    url: 'https://bsky.app/profile/axios.com',
    postsPerDay: 11.9,
  },
  {
    id: 'talkingpointsmemo',
    name: 'TPM',
    handle: '@talkingpointsmemo.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/talkingpointsmemo.com',
    url: 'https://bsky.app/profile/talkingpointsmemo.com',
    postsPerDay: 9.8,
  },
  {
    id: 'kylegriffin1',
    name: 'Kyle Griffin',
    handle: '@kylegriffin1.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/kylegriffin1.bsky.social',
    url: 'https://bsky.app/profile/kylegriffin1.bsky.social',
    postsPerDay: 6.5,
  },
  {
    id: 'davidcorn',
    name: 'David Corn',
    handle: '@davidcorn.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/davidcorn.bsky.social',
    url: 'https://bsky.app/profile/davidcorn.bsky.social',
    postsPerDay: 8.3,
  },
  {
    id: 'joycewhitevance',
    name: 'Joyce White Vance',
    handle: '@joycewhitevance.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/joycewhitevance.bsky.social',
    url: 'https://bsky.app/profile/joycewhitevance.bsky.social',
    postsPerDay: 6.9,
  },
  {
    id: 'katiephang',
    name: 'Katie Phang',
    handle: '@katiephang.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/katiephang.bsky.social',
    url: 'https://bsky.app/profile/katiephang.bsky.social',
    postsPerDay: 7.4,
  },
  {
    id: 'maddow',
    name: 'Rachel Maddow',
    handle: '@maddow.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/maddow.bsky.social',
    url: 'https://bsky.app/profile/maddow.bsky.social',
    postsPerDay: 15.9,
  },
  {
    id: 'adamkinzinger',
    name: 'Adam Kinzinger',
    handle: '@adamkinzinger.substack.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/adamkinzinger.substack.com',
    url: 'https://bsky.app/profile/adamkinzinger.substack.com',
    postsPerDay: 5.2,
  },
  {
    id: 'macfarlanenews',
    name: 'Scott MacFarlane',
    handle: '@macfarlanenews.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/macfarlanenews.bsky.social',
    url: 'https://bsky.app/profile/macfarlanenews.bsky.social',
    postsPerDay: 7.6,
  },
  {
    id: 'mehdirhasan',
    name: 'Mehdi Hasan',
    handle: '@mehdirhasan.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/mehdirhasan.bsky.social',
    url: 'https://bsky.app/profile/mehdirhasan.bsky.social',
    postsPerDay: 8.8,
  },
  {
    id: 'lincolnproject',
    name: 'The Lincoln Project',
    handle: '@lincolnproject.us',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/lincolnproject.us',
    url: 'https://bsky.app/profile/lincolnproject.us',
    postsPerDay: 2.8,
  },
  {
    id: 'warren-senate',
    name: 'Elizabeth Warren',
    handle: '@warren.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/warren.senate.gov',
    url: 'https://bsky.app/profile/warren.senate.gov',
    postsPerDay: 2.9,
  },
  {
    id: 'governor-ca',
    name: 'Governor Gavin Newsom',
    handle: '@governor.ca.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/governor.ca.gov',
    url: 'https://bsky.app/profile/governor.ca.gov',
    postsPerDay: 3.7,
  },
  {
    id: 'schiff-senate',
    name: 'Sen. Adam Schiff',
    handle: '@schiff.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/schiff.senate.gov',
    url: 'https://bsky.app/profile/schiff.senate.gov',
    postsPerDay: 2.9,
  },
  {
    id: 'whitehouse-senate',
    name: 'Senator Sheldon Whitehouse',
    handle: '@whitehouse.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/whitehouse.senate.gov',
    url: 'https://bsky.app/profile/whitehouse.senate.gov',
    postsPerDay: 3.3,
  },
  {
    id: 'newsagents',
    name: 'The News Agents',
    handle: '@newsagents.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/newsagents.bsky.social',
    url: 'https://bsky.app/profile/newsagents.bsky.social',
    postsPerDay: 2.8,
  },
  {
    id: 'schumer-senate',
    name: 'Chuck Schumer',
    handle: '@schumer.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/schumer.senate.gov',
    url: 'https://bsky.app/profile/schumer.senate.gov',
    postsPerDay: 2.4,
  },
  {
    id: 'pressley-house',
    name: 'Congresswoman Ayanna Pressley',
    handle: '@pressley.house.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/pressley.house.gov',
    url: 'https://bsky.app/profile/pressley.house.gov',
    postsPerDay: 2.4,
  },
  {
    id: 'thedailyshow',
    name: 'The Daily Show',
    handle: '@thedailyshow.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/thedailyshow.com',
    url: 'https://bsky.app/profile/thedailyshow.com',
    postsPerDay: 1.9,
  },
  {
    id: 'democracyforward',
    name: 'Democracy Forward',
    handle: '@democracyforward.org',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/democracyforward.org',
    url: 'https://bsky.app/profile/democracyforward.org',
    postsPerDay: 2.8,
  },
  {
    id: 'govpritzker',
    name: 'Governor JB Pritzker',
    handle: '@govpritzker.illinois.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/govpritzker.illinois.gov',
    url: 'https://bsky.app/profile/govpritzker.illinois.gov',
    postsPerDay: 2,
  },
  {
    id: 'brandyzadrozny',
    name: 'Brandy Zadrozny',
    handle: '@brandyzadrozny.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/brandyzadrozny.bsky.social',
    url: 'https://bsky.app/profile/brandyzadrozny.bsky.social',
    postsPerDay: 2.4,
  },
  {
    id: 'smith-senate',
    name: 'Tina Smith',
    handle: '@smith.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/smith.senate.gov',
    url: 'https://bsky.app/profile/smith.senate.gov',
    postsPerDay: 2,
  },
  {
    id: 'privateeyenews',
    name: 'Private Eye Magazine',
    handle: '@privateeyenews.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/privateeyenews.bsky.social',
    url: 'https://bsky.app/profile/privateeyenews.bsky.social',
    postsPerDay: 2.9,
  },
  {
    id: 'vanhollen-senate',
    name: 'Senator Chris Van Hollen',
    handle: '@vanhollen.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/vanhollen.senate.gov',
    url: 'https://bsky.app/profile/vanhollen.senate.gov',
    postsPerDay: 1.8,
  },
  {
    id: 'governorwalz',
    name: 'Governor Tim Walz',
    handle: '@governorwalz.mn.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/governorwalz.mn.gov',
    url: 'https://bsky.app/profile/governorwalz.mn.gov',
    postsPerDay: 1.3,
  },
  {
    id: 'briantylercohen',
    name: 'Brian Tyler Cohen',
    handle: '@briantylercohen.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T1',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/briantylercohen.bsky.social',
    url: 'https://bsky.app/profile/briantylercohen.bsky.social',
    postsPerDay: 1.5,
  }
];

// -----------------------------------------------------------------------------
// T2 - STANDARD SOURCES (76) - Fetch async, animate in
// -----------------------------------------------------------------------------
export const tier2Sources: TieredSource[] = [
  // === BBC NEWS (bluecrawler top 1000) ===
  {
    id: 'bbc-newsnight',
    name: 'BBC Newsnight',
    handle: '@bbcnewsnight.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bbcnewsnight.bsky.social',
    url: 'https://bsky.app/profile/bbcnewsnight.bsky.social',
    postsPerDay: 1.1,
  },
  // === NEW OSINT ACCOUNTS (Jan 2026) ===
  {
    id: 'bellingcat',
    name: 'Bellingcat',
    handle: '@bellingcat.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 95,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bellingcat.com',
    url: 'https://bsky.app/profile/bellingcat.com',
    postsPerDay: 2.9,
  },
  {
    id: 'tatarigami',
    name: 'Tatarigami',
    handle: '@tatarigami.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 90,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/tatarigami.bsky.social',
    url: 'https://bsky.app/profile/tatarigami.bsky.social',
    postsPerDay: 1.5,
  },
  {
    id: 'geoconfirmed',
    name: 'GeoConfirmed',
    handle: '@geoconfirmed.org',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/geoconfirmed.org',
    url: 'https://bsky.app/profile/geoconfirmed.org',
    postsPerDay: 0.3,
  },
  {
    id: 'malachy-browne',
    name: 'Malachy Browne',
    handle: '@malachy.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/malachy.bsky.social',
    url: 'https://bsky.app/profile/malachy.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'bosphorus-observer',
    name: 'Bosphorus Observer',
    handle: '@yoruk.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 85,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/yoruk.bsky.social',
    url: 'https://bsky.app/profile/yoruk.bsky.social',
    postsPerDay: 1.5,
  },
  {
    id: 'all-source-news',
    name: 'All Source News',
    handle: '@allsourcenews.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/allsourcenews.bsky.social',
    url: 'https://bsky.app/profile/allsourcenews.bsky.social',
    postsPerDay: 1.4,
  },
  // === ORIGINAL T2 SOURCES ===
  {
    id: 'us-dhs',
    name: 'DHS Homeland Security',
    handle: '@homelandgov.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/homelandgov.bsky.social',
    url: 'https://bsky.app/profile/homelandgov.bsky.social',
    postsPerDay: 1.1,
  },
  {
    id: 'eu-eeas',
    name: 'EU Diplomacy (EEAS)',
    handle: '@eudiplomacy.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/eudiplomacy.bsky.social',
    url: 'https://bsky.app/profile/eudiplomacy.bsky.social',
    postsPerDay: 0.8,
  },
  {
    id: 'oliver-alexander',
    name: 'Oliver Alexander',
    handle: '@oalexanderdk.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/oalexanderdk.bsky.social',
    url: 'https://bsky.app/profile/oalexanderdk.bsky.social',
    postsPerDay: 2.6,
  },
  {
    id: 'michael-kofman',
    name: 'Michael Kofman',
    handle: '@michaelkofman.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/michaelkofman.bsky.social',
    url: 'https://bsky.app/profile/michaelkofman.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'elint-news',
    name: 'ELINT News',
    handle: '@elintnews.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/elintnews.bsky.social',
    url: 'https://bsky.app/profile/elintnews.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'merip',
    name: 'MERIP',
    handle: '@merip.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/merip.bsky.social',
    url: 'https://bsky.app/profile/merip.bsky.social',
    postsPerDay: 1.5,
  },
  {
    id: 'ryan-mcbeth',
    name: 'Ryan McBeth',
    handle: '@ryanmcbeth.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ryanmcbeth.bsky.social',
    url: 'https://bsky.app/profile/ryanmcbeth.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'china-media-project',
    name: 'China Media Project',
    handle: '@chinamediaproject.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/chinamediaproject.bsky.social',
    url: 'https://bsky.app/profile/chinamediaproject.bsky.social',
    postsPerDay: 0.6,
  },
  {
    id: 'chinafile',
    name: 'ChinaFile',
    handle: '@chinafile.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/chinafile.bsky.social',
    url: 'https://bsky.app/profile/chinafile.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'ncuscr',
    name: 'National Committee on US-China Relations',
    handle: '@ncuscr.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ncuscr.bsky.social',
    url: 'https://bsky.app/profile/ncuscr.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'andrei-netto',
    name: 'Andrei Netto',
    handle: '@andreinetto.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'latam' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/andreinetto.bsky.social',
    url: 'https://bsky.app/profile/andreinetto.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'michael-weintraub',
    name: 'Michael Weintraub',
    handle: '@miweintraub83.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'latam' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/miweintraub83.bsky.social',
    url: 'https://bsky.app/profile/miweintraub83.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'ian-bremmer',
    name: 'Ian Bremmer',
    handle: '@ianbremmer.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ianbremmer.com',
    url: 'https://bsky.app/profile/ianbremmer.com',
    postsPerDay: 0.8,
  },
  {
    id: 'jeffrey-lewis',
    name: 'Jeffrey Lewis (Arms Control Wonk)',
    handle: '@armscontrolwonk.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/armscontrolwonk.bsky.social',
    url: 'https://bsky.app/profile/armscontrolwonk.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'alexander-kmentt',
    name: 'Alexander Kmentt',
    handle: '@akmentt.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/akmentt.bsky.social',
    url: 'https://bsky.app/profile/akmentt.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'michael-kofman',
    name: 'Michael Kofman',
    handle: '@michaelkofman.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/michaelkofman.bsky.social',
    url: 'https://bsky.app/profile/michaelkofman.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'michael-hayden',
    name: 'Gen Michael Hayden',
    handle: '@genmhayden.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/genmhayden.bsky.social',
    url: 'https://bsky.app/profile/genmhayden.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'liveuamap',
    name: 'Liveuamap',
    handle: '@liveuamap.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/liveuamap.com',
    url: 'https://bsky.app/profile/liveuamap.com',
    postsPerDay: 0.4,
  },
  {
    id: 'christopher-miller',
    name: 'Christopher Miller',
    handle: '@christopherjm.ft.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/christopherjm.ft.com',
    url: 'https://bsky.app/profile/christopherjm.ft.com',
    postsPerDay: 1.5,
  },
  {
    id: 'steve-rosenberg',
    name: 'Steve Rosenberg',
    handle: '@bbcstever.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bbcstever.bsky.social',
    url: 'https://bsky.app/profile/bbcstever.bsky.social',
    postsPerDay: 0.6,
  },
  {
    id: 'oz-katerji',
    name: 'Oz Katerji',
    handle: '@ozkaterji.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ozkaterji.bsky.social',
    url: 'https://bsky.app/profile/ozkaterji.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'david-sanger',
    name: 'David E. Sanger',
    handle: '@sangernyt.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/sangernyt.bsky.social',
    url: 'https://bsky.app/profile/sangernyt.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'charlie-savage',
    name: 'Charlie Savage',
    handle: '@charliesavage.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/charliesavage.bsky.social',
    url: 'https://bsky.app/profile/charliesavage.bsky.social',
    postsPerDay: 0.5,
  },
  {
    id: 'richard-milne',
    name: 'Richard Milne',
    handle: '@richardmilne.ft.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/richardmilne.ft.com',
    url: 'https://bsky.app/profile/richardmilne.ft.com',
    postsPerDay: 0.1,
  },
  {
    id: 'kate-conger',
    name: 'Kate Conger',
    handle: '@kateconger.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/kateconger.com',
    url: 'https://bsky.app/profile/kateconger.com',
    postsPerDay: 1.3,
  },
  {
    id: 'christiaan-triebert',
    name: 'Christiaan Triebert',
    handle: '@trbrtc.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/trbrtc.bsky.social',
    url: 'https://bsky.app/profile/trbrtc.bsky.social',
    postsPerDay: 2.7,
  },
  {
    id: 'julian-barnes',
    name: 'Julian Barnes',
    handle: '@julianbarnes.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/julianbarnes.bsky.social',
    url: 'https://bsky.app/profile/julianbarnes.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'eric-lipton',
    name: 'Eric Lipton',
    handle: '@ericlipton.nytimes.com',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ericlipton.nytimes.com',
    url: 'https://bsky.app/profile/ericlipton.nytimes.com',
    postsPerDay: 3.5,
  },
  {
    id: 'joe-tidy',
    name: 'Joe Tidy',
    handle: '@joetidy.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/joetidy.bsky.social',
    url: 'https://bsky.app/profile/joetidy.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'tom-phillips-guardian',
    name: 'Tom Phillips',
    handle: '@tomphillips.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'latam' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/tomphillips.bsky.social',
    url: 'https://bsky.app/profile/tomphillips.bsky.social',
    postsPerDay: 0.6,
  },
  {
    id: 'andy-kroll',
    name: 'Andy Kroll',
    handle: '@andykroll.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/andykroll.bsky.social',
    url: 'https://bsky.app/profile/andykroll.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'heather-vogell',
    name: 'Heather Vogell',
    handle: '@heathervogell.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/heathervogell.bsky.social',
    url: 'https://bsky.app/profile/heathervogell.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'illia-ponomarenko',
    name: 'Illia Ponomarenko',
    handle: '@ioponomarenko.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ioponomarenko.bsky.social',
    url: 'https://bsky.app/profile/ioponomarenko.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'simon-allison',
    name: 'Simon Allison',
    handle: '@simonallison.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/simonallison.bsky.social',
    url: 'https://bsky.app/profile/simonallison.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'kashmir-hill',
    name: 'Kashmir Hill',
    handle: '@kashhill.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/kashhill.bsky.social',
    url: 'https://bsky.app/profile/kashhill.bsky.social',
    postsPerDay: 1,
  },
  {
    id: 'atlantic-council',
    name: 'Atlantic Council',
    handle: '@atlanticcouncil.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/atlanticcouncil.bsky.social',
    url: 'https://bsky.app/profile/atlanticcouncil.bsky.social',
    postsPerDay: 0.7,
  },
  {
    id: 'tnsr',
    name: 'Texas National Security Review',
    handle: '@tnsr.org',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/tnsr.org',
    url: 'https://bsky.app/profile/tnsr.org',
    postsPerDay: 0.9,
  },
  {
    id: 'kyiv-insider',
    name: 'Kyiv Insider',
    handle: '@kyivinsider.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/kyivinsider.bsky.social',
    url: 'https://bsky.app/profile/kyivinsider.bsky.social',
    postsPerDay: 0.5,
  },
  {
    id: 'unhcr',
    name: 'UNHCR',
    handle: '@unhcr.org',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/unhcr.org',
    url: 'https://bsky.app/profile/unhcr.org',
    postsPerDay: 1.5,
  },
  {
    id: 'julia-ioffe',
    name: 'Julia Ioffe',
    handle: '@juliaioffe.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/juliaioffe.bsky.social',
    url: 'https://bsky.app/profile/juliaioffe.bsky.social',
    postsPerDay: 0.8,
  },
  {
    id: 'michael-weiss',
    name: 'Michael Weiss',
    handle: '@michaeldweiss.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/michaeldweiss.bsky.social',
    url: 'https://bsky.app/profile/michaeldweiss.bsky.social',
    postsPerDay: 1.1,
  },
  {
    id: 'abc-news',
    name: 'ABC News',
    handle: '@abcnews.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/abcnews.bsky.social',
    url: 'https://bsky.app/profile/abcnews.bsky.social',
    postsPerDay: 0.5,
  },
  {
    id: 'paul-krugman',
    name: 'Paul Krugman',
    handle: '@pkrugman.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/pkrugman.bsky.social',
    url: 'https://bsky.app/profile/pkrugman.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'asia-society',
    name: 'Asia Society',
    handle: '@asiasociety.org',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/asiasociety.org',
    url: 'https://bsky.app/profile/asiasociety.org',
    postsPerDay: 0.9,
  },
  {
    id: 'neri-zilber',
    name: 'Neri Zilber',
    handle: '@nerizilber.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/nerizilber.bsky.social',
    url: 'https://bsky.app/profile/nerizilber.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'joyce-karam',
    name: 'Joyce Karam',
    handle: '@joycekaram.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/joycekaram.bsky.social',
    url: 'https://bsky.app/profile/joycekaram.bsky.social',
    postsPerDay: 0.5,
  },
  {
    id: 'arms-control-wonk',
    name: 'Arms Control Wonk',
    handle: '@armscontrolwonk.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/armscontrolwonk.bsky.social',
    url: 'https://bsky.app/profile/armscontrolwonk.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'ian-bremmer',
    name: 'Ian Bremmer',
    handle: '@ianbremmer.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ianbremmer.com',
    url: 'https://bsky.app/profile/ianbremmer.com',
    postsPerDay: 0.8,
  },
  {
    id: 'michael-mcfaul',
    name: 'Michael McFaul',
    handle: '@mcfaul.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/mcfaul.bsky.social',
    url: 'https://bsky.app/profile/mcfaul.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'noaa',
    name: 'NOAA',
    handle: '@noaa.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/noaa.gov',
    url: 'https://bsky.app/profile/noaa.gov',
    postsPerDay: 0.7,
  },
  // === BLUECRAWLER TOP 1000 T2 (Jan 2026) ===
  {
    id: 'keithedwards',
    name: 'Keith Edwards',
    handle: '@keithedwards.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/keithedwards.bsky.social',
    url: 'https://bsky.app/profile/keithedwards.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'markzaidesq',
    name: 'Mark Zaid, Esq',
    handle: '@markzaidesq.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/markzaidesq.bsky.social',
    url: 'https://bsky.app/profile/markzaidesq.bsky.social',
    postsPerDay: 0.9,
  },
  {
    id: 'sanders-senate',
    name: 'Senator Bernie Sanders',
    handle: '@sanders.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/sanders.senate.gov',
    url: 'https://bsky.app/profile/sanders.senate.gov',
    postsPerDay: 1.4,
  },
  {
    id: 'wyden-senate',
    name: 'Senator Ron Wyden',
    handle: '@wyden.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/wyden.senate.gov',
    url: 'https://bsky.app/profile/wyden.senate.gov',
    postsPerDay: 1.5,
  },
  {
    id: 'crockett-house',
    name: 'Congresswoman Jasmine Crockett',
    handle: '@crockett.house.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/crockett.house.gov',
    url: 'https://bsky.app/profile/crockett.house.gov',
    postsPerDay: 1.1,
  },
  {
    id: 'raskin-house',
    name: 'Rep. Jamie Raskin',
    handle: '@raskin.house.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/raskin.house.gov',
    url: 'https://bsky.app/profile/raskin.house.gov',
    postsPerDay: 1.1,
  },
  {
    id: 'booker-senate',
    name: 'Sen. Cory Booker',
    handle: '@booker.senate.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/booker.senate.gov',
    url: 'https://bsky.app/profile/booker.senate.gov',
    postsPerDay: 1,
  },
  {
    id: 'juliadavisnews',
    name: 'Julia Davis',
    handle: '@juliadavisnews.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/juliadavisnews.bsky.social',
    url: 'https://bsky.app/profile/juliadavisnews.bsky.social',
    postsPerDay: 1,
  },
  {
    id: 'algreen-house',
    name: 'U.S. Representative Al Green',
    handle: '@algreen.house.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/algreen.house.gov',
    url: 'https://bsky.app/profile/algreen.house.gov',
    postsPerDay: 0.8,
  },
  {
    id: 'elonjet',
    name: 'Elon Jet Tracking',
    handle: '@elonjet.net',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/elonjet.net',
    url: 'https://bsky.app/profile/elonjet.net',
    postsPerDay: 1.6,
  },
  {
    id: 'petebuttigieg',
    name: 'Pete Buttigieg',
    handle: '@petebuttigieg.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/petebuttigieg.bsky.social',
    url: 'https://bsky.app/profile/petebuttigieg.bsky.social',
    postsPerDay: 0.8,
  },
  {
    id: 'barackobama',
    name: 'Barack Obama',
    handle: '@barackobama.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/barackobama.bsky.social',
    url: 'https://bsky.app/profile/barackobama.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'hillaryclinton',
    name: 'Hillary Rodham Clinton',
    handle: '@hillaryclinton.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/hillaryclinton.bsky.social',
    url: 'https://bsky.app/profile/hillaryclinton.bsky.social',
    postsPerDay: 0.6,
  },
  {
    id: 'ocasio-cortez-house',
    name: 'Rep. Alexandria Ocasio-Cortez',
    handle: '@ocasio-cortez.house.gov',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ocasio-cortez.house.gov',
    url: 'https://bsky.app/profile/ocasio-cortez.house.gov',
    postsPerDay: 0.5,
  },
  {
    id: 'fiveminutenews',
    name: 'FIVE MINUTE NEWS',
    handle: '@fiveminutenews.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/fiveminutenews.bsky.social',
    url: 'https://bsky.app/profile/fiveminutenews.bsky.social',
    postsPerDay: 1.3,
  },
  {
    id: 'weeklyshowpodcast',
    name: 'The Weekly Show with Jon Stewart',
    handle: '@weeklyshowpodcast.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/weeklyshowpodcast.bsky.social',
    url: 'https://bsky.app/profile/weeklyshowpodcast.bsky.social',
    postsPerDay: 1,
  },
  {
    id: 'xkcd',
    name: 'Randall Munroe (xkcd)',
    handle: '@xkcd.com',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/xkcd.com',
    url: 'https://bsky.app/profile/xkcd.com',
    postsPerDay: 0.5,
  },
  {
    id: 'mindyanns',
    name: 'Mindy Schwartz',
    handle: '@mindyanns.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/mindyanns.bsky.social',
    url: 'https://bsky.app/profile/mindyanns.bsky.social',
    postsPerDay: 0.6,
  },
  {
    id: 'jemelehill',
    name: 'Jemele Hill',
    handle: '@jemelehill.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T2',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jemelehill.bsky.social',
    url: 'https://bsky.app/profile/jemelehill.bsky.social',
    postsPerDay: 0.6,
  }
];

// -----------------------------------------------------------------------------
// T3 - ARCHIVE SOURCES (24) - Fetch on-demand
// -----------------------------------------------------------------------------
export const tier3Sources: TieredSource[] = [
  // === NEW OSINT ACCOUNTS (Jan 2026) ===
  {
    id: 'ukraine-control-map',
    name: 'Ukraine Control Map',
    handle: '@uacontrolmap.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 90,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/uacontrolmap.bsky.social',
    url: 'https://bsky.app/profile/uacontrolmap.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'aric-toler',
    name: 'Aric Toler',
    handle: '@aric.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 90,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/aric.bsky.social',
    url: 'https://bsky.app/profile/aric.bsky.social',
    postsPerDay: 0.7,
  },
  {
    id: 'faytuks',
    name: 'Faytuks News',
    handle: '@faytuks.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/faytuks.bsky.social',
    url: 'https://bsky.app/profile/faytuks.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'alison-killing',
    name: 'Alison Killing',
    handle: '@alisonkilling.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 85,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/alisonkilling.bsky.social',
    url: 'https://bsky.app/profile/alisonkilling.bsky.social',
    postsPerDay: 0.7,
  },
  // === ORIGINAL T3 SOURCES ===
  {
    id: 'us-state-dept',
    name: 'US State Department',
    handle: '@state-department.bsky.social',
    platform: 'bluesky',
    tier: 'official',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/state-department.bsky.social',
    url: 'https://bsky.app/profile/state-department.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'ukraine-map',
    name: 'Ukraine Battle Map',
    handle: '@ukrainemap.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/ukrainemap.bsky.social',
    url: 'https://bsky.app/profile/ukrainemap.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'taiwan-monitor',
    name: 'Taiwan Security Monitor',
    handle: '@taiwanmonitor.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/taiwanmonitor.bsky.social',
    url: 'https://bsky.app/profile/taiwanmonitor.bsky.social',
    postsPerDay: 0.5,
  },
  {
    id: 'indo-pacific-insight',
    name: 'Indo-Pacific Insight',
    handle: '@indopacificinsight.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/indopacificinsight.bsky.social',
    url: 'https://bsky.app/profile/indopacificinsight.bsky.social',
    postsPerDay: 0.5,
  },
  {
    id: 'geoinsider',
    name: 'GeoInsider',
    handle: '@geoinsider.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/geoinsider.bsky.social',
    url: 'https://bsky.app/profile/geoinsider.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'ukraine-air-alerts',
    name: 'Ukraine Air Raid Alert Map',
    handle: '@alerts.in.ua',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/alerts.in.ua',
    url: 'https://bsky.app/profile/alerts.in.ua',
    postsPerDay: 0.1,
  },
  {
    id: 'barak-ravid',
    name: 'Barak Ravid',
    handle: '@barakravid.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/barakravid.bsky.social',
    url: 'https://bsky.app/profile/barakravid.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'avi-scharf',
    name: 'Avi Scharf',
    handle: '@avischarf.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/avischarf.bsky.social',
    url: 'https://bsky.app/profile/avischarf.bsky.social',
    postsPerDay: 0.4,
  },
  {
    id: 'colum-lynch',
    name: 'Colum Lynch',
    handle: '@columlynch.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/columlynch.bsky.social',
    url: 'https://bsky.app/profile/columlynch.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'brian-finucane',
    name: 'Brian Finucane',
    handle: '@bcfinucane.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bcfinucane.bsky.social',
    url: 'https://bsky.app/profile/bcfinucane.bsky.social',
    postsPerDay: 51.7,
  },
  {
    id: 'jeremy-page',
    name: 'Jeremy Page',
    handle: '@jnbpage.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jnbpage.bsky.social',
    url: 'https://bsky.app/profile/jnbpage.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'hannah-murphy',
    name: 'Hannah Murphy',
    handle: '@mshannahmurphy.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/mshannahmurphy.bsky.social',
    url: 'https://bsky.app/profile/mshannahmurphy.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'jodi-kantor',
    name: 'Jodi Kantor',
    handle: '@jodikantor.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'us-domestic' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/jodikantor.bsky.social',
    url: 'https://bsky.app/profile/jodikantor.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'zoe-kleinman',
    name: 'Zoe Kleinman',
    handle: '@zsk.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/zsk.bsky.social',
    url: 'https://bsky.app/profile/zsk.bsky.social',
    postsPerDay: 0.3,
  },
  {
    id: 'daniel-sandford',
    name: 'Daniel Sandford',
    handle: '@bbcdaniels.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bbcdaniels.bsky.social',
    url: 'https://bsky.app/profile/bbcdaniels.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'dominic-casciani',
    name: 'Dominic Casciani',
    handle: '@bbcdomc.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/bbcdomc.bsky.social',
    url: 'https://bsky.app/profile/bbcdomc.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'matthew-cappucci',
    name: 'Matthew Cappucci',
    handle: '@matthewcappucci.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'all' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/matthewcappucci.bsky.social',
    url: 'https://bsky.app/profile/matthewcappucci.bsky.social',
    postsPerDay: 0.2,
  },
  {
    id: 'masha-gessen',
    name: 'Masha Gessen',
    handle: '@mashagessen.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'ukraine' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/mashagessen.bsky.social',
    url: 'https://bsky.app/profile/mashagessen.bsky.social',
    postsPerDay: 0,
  },
  {
    id: 'bill-bishop',
    name: 'Bill Bishop',
    handle: '@billbishop.bsky.social',
    platform: 'bluesky',
    tier: 'osint',
    fetchTier: 'T3',
    confidence: 80,
    region: 'china-taiwan' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/billbishop.bsky.social',
    url: 'https://bsky.app/profile/billbishop.bsky.social',
    postsPerDay: 0.1,
  },
  {
    id: 'barak-ravid',
    name: 'Barak Ravid',
    handle: '@barakravid.bsky.social',
    platform: 'bluesky',
    tier: 'reporter',
    fetchTier: 'T3',
    confidence: 80,
    region: 'middle-east' as WatchpointId,
    feedUrl: 'https://bsky.app/profile/barakravid.bsky.social',
    url: 'https://bsky.app/profile/barakravid.bsky.social',
    postsPerDay: 0.3,
  }
];

// -----------------------------------------------------------------------------
// COMBINED EXPORTS
// -----------------------------------------------------------------------------
export const allTieredSources: TieredSource[] = [
  ...tier1Sources,
  ...tier2Sources,
  ...tier3Sources,
];

export function getSourcesByTier(tier: FetchTier): TieredSource[] {
  switch (tier) {
    case 'T1': return tier1Sources;
    case 'T2': return tier2Sources;
    case 'T3': return tier3Sources;
  }
}

export function getSourcesByRegion(region: WatchpointId): TieredSource[] {
  if (region === 'all') return allTieredSources;
  return allTieredSources.filter(s => s.region === region || s.region === 'all');
}

// Legacy export for compatibility
export const allSources = allTieredSources;
